### ISSUE TITLE
IngressCore: Simpler implementation

### ISSUE THREAD

**Issue by sadigaxund** [sadigaxund/pypelineer#8]
In a very simple example, if a user doesn't implement constructor or destructor in case (e.g. when Type=INPUT), then make sure that user could use the core without refering to the context manager protocol and just initializes the core as an instance using __init__. Currently, I get:

Traceback (most recent call last):
  File "******", line 24, in <module>
    for number, odd_or_even in oddity:
  File "******", line 101, in __next__
    return next(self.handler)
                ^^^^^^^^^^^^

**Comment by sadigaxund** [comment]
In case of EgressCore, lessen the implementation requirements. sometimes it's unnecesarry just to have other function if not needed.
